/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BadgesRouteImport } from './routes/badges'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as ToolsNotebookRouteImport } from './routes/tools.notebook'
import { Route as ToolsLabsRouteImport } from './routes/tools.labs'
import { Route as ToolsIdeRouteImport } from './routes/tools.ide'
import { Route as PathsLiveCollaborationRouteImport } from './routes/paths.live-collaboration'
import { Route as PathsIndustryLinkRouteImport } from './routes/paths.industry-link'
import { Route as PathsDsaLabRouteImport } from './routes/paths.dsa-lab'
import { Route as PathsCareerSimRouteImport } from './routes/paths.career-sim'
import { Route as PathsBlockchainBadgingRouteImport } from './routes/paths.blockchain-badging'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgesRoute = BadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsNotebookRoute = ToolsNotebookRouteImport.update({
  id: '/tools/notebook',
  path: '/tools/notebook',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsLabsRoute = ToolsLabsRouteImport.update({
  id: '/tools/labs',
  path: '/tools/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIdeRoute = ToolsIdeRouteImport.update({
  id: '/tools/ide',
  path: '/tools/ide',
  getParentRoute: () => rootRouteImport,
} as any)
const PathsLiveCollaborationRoute = PathsLiveCollaborationRouteImport.update({
  id: '/paths/live-collaboration',
  path: '/paths/live-collaboration',
  getParentRoute: () => rootRouteImport,
} as any)
const PathsIndustryLinkRoute = PathsIndustryLinkRouteImport.update({
  id: '/paths/industry-link',
  path: '/paths/industry-link',
  getParentRoute: () => rootRouteImport,
} as any)
const PathsDsaLabRoute = PathsDsaLabRouteImport.update({
  id: '/paths/dsa-lab',
  path: '/paths/dsa-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const PathsCareerSimRoute = PathsCareerSimRouteImport.update({
  id: '/paths/career-sim',
  path: '/paths/career-sim',
  getParentRoute: () => rootRouteImport,
} as any)
const PathsBlockchainBadgingRoute = PathsBlockchainBadgingRouteImport.update({
  id: '/paths/blockchain-badging',
  path: '/paths/blockchain-badging',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/badges': typeof BadgesRoute
  '/dashboard': typeof DashboardRoute
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/paths/blockchain-badging': typeof PathsBlockchainBadgingRoute
  '/paths/career-sim': typeof PathsCareerSimRoute
  '/paths/dsa-lab': typeof PathsDsaLabRoute
  '/paths/industry-link': typeof PathsIndustryLinkRoute
  '/paths/live-collaboration': typeof PathsLiveCollaborationRoute
  '/tools/ide': typeof ToolsIdeRoute
  '/tools/labs': typeof ToolsLabsRoute
  '/tools/notebook': typeof ToolsNotebookRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/badges': typeof BadgesRoute
  '/dashboard': typeof DashboardRoute
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/paths/blockchain-badging': typeof PathsBlockchainBadgingRoute
  '/paths/career-sim': typeof PathsCareerSimRoute
  '/paths/dsa-lab': typeof PathsDsaLabRoute
  '/paths/industry-link': typeof PathsIndustryLinkRoute
  '/paths/live-collaboration': typeof PathsLiveCollaborationRoute
  '/tools/ide': typeof ToolsIdeRoute
  '/tools/labs': typeof ToolsLabsRoute
  '/tools/notebook': typeof ToolsNotebookRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/badges': typeof BadgesRoute
  '/dashboard': typeof DashboardRoute
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/paths/blockchain-badging': typeof PathsBlockchainBadgingRoute
  '/paths/career-sim': typeof PathsCareerSimRoute
  '/paths/dsa-lab': typeof PathsDsaLabRoute
  '/paths/industry-link': typeof PathsIndustryLinkRoute
  '/paths/live-collaboration': typeof PathsLiveCollaborationRoute
  '/tools/ide': typeof ToolsIdeRoute
  '/tools/labs': typeof ToolsLabsRoute
  '/tools/notebook': typeof ToolsNotebookRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/badges'
    | '/dashboard'
    | '/feedback'
    | '/login'
    | '/signup'
    | '/paths/blockchain-badging'
    | '/paths/career-sim'
    | '/paths/dsa-lab'
    | '/paths/industry-link'
    | '/paths/live-collaboration'
    | '/tools/ide'
    | '/tools/labs'
    | '/tools/notebook'
    | '/u/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/badges'
    | '/dashboard'
    | '/feedback'
    | '/login'
    | '/signup'
    | '/paths/blockchain-badging'
    | '/paths/career-sim'
    | '/paths/dsa-lab'
    | '/paths/industry-link'
    | '/paths/live-collaboration'
    | '/tools/ide'
    | '/tools/labs'
    | '/tools/notebook'
    | '/u/$username'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/badges'
    | '/dashboard'
    | '/feedback'
    | '/login'
    | '/signup'
    | '/paths/blockchain-badging'
    | '/paths/career-sim'
    | '/paths/dsa-lab'
    | '/paths/industry-link'
    | '/paths/live-collaboration'
    | '/tools/ide'
    | '/tools/labs'
    | '/tools/notebook'
    | '/u/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BadgesRoute: typeof BadgesRoute
  DashboardRoute: typeof DashboardRoute
  FeedbackRoute: typeof FeedbackRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  PathsBlockchainBadgingRoute: typeof PathsBlockchainBadgingRoute
  PathsCareerSimRoute: typeof PathsCareerSimRoute
  PathsDsaLabRoute: typeof PathsDsaLabRoute
  PathsIndustryLinkRoute: typeof PathsIndustryLinkRoute
  PathsLiveCollaborationRoute: typeof PathsLiveCollaborationRoute
  ToolsIdeRoute: typeof ToolsIdeRoute
  ToolsLabsRoute: typeof ToolsLabsRoute
  ToolsNotebookRoute: typeof ToolsNotebookRoute
  UUsernameRoute: typeof UUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badges': {
      id: '/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof BadgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/notebook': {
      id: '/tools/notebook'
      path: '/tools/notebook'
      fullPath: '/tools/notebook'
      preLoaderRoute: typeof ToolsNotebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/labs': {
      id: '/tools/labs'
      path: '/tools/labs'
      fullPath: '/tools/labs'
      preLoaderRoute: typeof ToolsLabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/ide': {
      id: '/tools/ide'
      path: '/tools/ide'
      fullPath: '/tools/ide'
      preLoaderRoute: typeof ToolsIdeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paths/live-collaboration': {
      id: '/paths/live-collaboration'
      path: '/paths/live-collaboration'
      fullPath: '/paths/live-collaboration'
      preLoaderRoute: typeof PathsLiveCollaborationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paths/industry-link': {
      id: '/paths/industry-link'
      path: '/paths/industry-link'
      fullPath: '/paths/industry-link'
      preLoaderRoute: typeof PathsIndustryLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paths/dsa-lab': {
      id: '/paths/dsa-lab'
      path: '/paths/dsa-lab'
      fullPath: '/paths/dsa-lab'
      preLoaderRoute: typeof PathsDsaLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paths/career-sim': {
      id: '/paths/career-sim'
      path: '/paths/career-sim'
      fullPath: '/paths/career-sim'
      preLoaderRoute: typeof PathsCareerSimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paths/blockchain-badging': {
      id: '/paths/blockchain-badging'
      path: '/paths/blockchain-badging'
      fullPath: '/paths/blockchain-badging'
      preLoaderRoute: typeof PathsBlockchainBadgingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BadgesRoute: BadgesRoute,
  DashboardRoute: DashboardRoute,
  FeedbackRoute: FeedbackRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  PathsBlockchainBadgingRoute: PathsBlockchainBadgingRoute,
  PathsCareerSimRoute: PathsCareerSimRoute,
  PathsDsaLabRoute: PathsDsaLabRoute,
  PathsIndustryLinkRoute: PathsIndustryLinkRoute,
  PathsLiveCollaborationRoute: PathsLiveCollaborationRoute,
  ToolsIdeRoute: ToolsIdeRoute,
  ToolsLabsRoute: ToolsLabsRoute,
  ToolsNotebookRoute: ToolsNotebookRoute,
  UUsernameRoute: UUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
